# Salvar e carregar arrays

In [2]:
import numpy as np

In [3]:
# criando dois arrays
array_1 = np.array([0, 1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8, 9])

### `np.save`

In [4]:
# salva o array em formato binário
np.save(file='array_1_file', arr=array_1)

In [5]:
!ls

array_1_file.npy  sample_data


In [6]:
!head array_1_file.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (5,), }                                                            


### `np.load`

In [7]:
# carregando um array a partir de um arquivo
array_1_loaded = np.load(file='/content/array_1_file.npy')
array_1_loaded

array([0, 1, 2, 3, 4])

### `np.savez`

In [8]:
# salva mais de um array no mesmo arquivo
np.savez('array_savez', array_1, array_2)

In [9]:
!ls

array_1_file.npy  array_savez.npz  sample_data


In [10]:
# carregando um array a partir de um arquivo
arrays_loaded = np.load(file='/content/array_savez.npz')
arrays_loaded

NpzFile '/content/array_savez.npz' with keys: arr_0, arr_1

In [11]:
arrays_loaded['arr_0']

array([0, 1, 2, 3, 4])

In [12]:
arrays_loaded['arr_1']

array([5, 6, 7, 8, 9])

### `np.savez_compressed`

In [13]:
# salva um ou mais de um array no mesmo arquivo comprimido
np.savez_compressed('arrays_compacted', array_1, array_2)

In [14]:
!ls

array_1_file.npy  array_savez.npz  arrays_compacted.npz  sample_data


In [15]:
!ls -la

total 28
drwxr-xr-x 1 root root 4096 Jun 28 21:53 .
drwxr-xr-x 1 root root 4096 Jun 28 21:40 ..
-rw-r--r-- 1 root root  168 Jun 28 21:47 array_1_file.npy
-rw-r--r-- 1 root root  586 Jun 28 21:50 array_savez.npz
-rw-r--r-- 1 root root  413 Jun 28 21:53 arrays_compacted.npz
drwxr-xr-x 4 root root 4096 Jun 27 13:25 .config
drwxr-xr-x 1 root root 4096 Jun 27 13:26 sample_data


In [16]:
# carregando um array a partir de um arquivo
arrays_loaded = np.load(file='/content/arrays_compacted.npz')
arrays_loaded

NpzFile '/content/arrays_compacted.npz' with keys: arr_0, arr_1

### `np.savetxt`

In [17]:
array_2d = np.vstack([array_1, array_2])
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
np.savetxt(fname='array_csv.csv', X=array_2d)

In [19]:
!ls

array_1_file.npy  array_csv.csv  array_savez.npz  arrays_compacted.npz	sample_data


In [20]:
!head array_csv.csv

0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
5.000000000000000000e+00 6.000000000000000000e+00 7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00


In [21]:
np.savetxt(fname='array_csv.csv', X=array_2d, fmt='%s')

In [22]:
!head array_csv.csv

0 1 2 3 4
5 6 7 8 9


In [23]:
np.savetxt(fname = 'array_csv.csv', X = array_2d, fmt = '%s', delimiter = ',')

In [24]:
!head array_csv.csv

0,1,2,3,4
5,6,7,8,9


### `np.loadtxt`

In [25]:
array_csv_loaded = np.loadtxt(fname='/content/array_csv.csv', dtype=int, delimiter=',')
array_csv_loaded

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

💡 `np.loadtxt` têm outros parâmetros interessantes, como:
- `skiprows`: número de linhas para pular do início do arquivo
- `usecols`: índices das colunas para carregar
- `max_rows`: número máximo de linhas para carregar

Outros métodos estão disponíveis conforme a documentação: https://numpy.org/devdocs/reference/routines.io.html#input-and-output