## Arrays preenchidos

### `np.zeros`

O `np.zeros` é uma função do módulo NumPy que cria um novo array com todos os elementos inicializados como zero.

In [ ]:
import numpy as np


In [ ]:
np.zeros(shape=3) # cria um array de zeros com 3 elementos

array([0., 0., 0.])

In [ ]:
np.zeros(shape=(2,3)) # cria uma matriz com 2 linhas e 3 colunas

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(shape=(2,3)).dtype # observe que o tipo padrão dos elementos é float64

dtype('float64')

In [ ]:
# criando uma matrix de zeros a partir do shape de outra matriz
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

array_zeros = np.zeros_like(array)
array_zeros

array([[0, 0, 0],
       [0, 0, 0]])

### `np.ones`

O `np.ones` é uma função do módulo NumPy que cria um novo array com todos os elementos inicializados como um.

In [ ]:
np.ones(shape=(2, 3)) # cria uma matriz de 1s com 2 linhas e 3 colunas

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# criando uma matrix de 1s a partir do shape de outra matriz
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

array_ones = np.ones_like(array)
array_ones

array([[1, 1, 1],
       [1, 1, 1]])

### `np.full`

O `np.full` é uma função do módulo NumPy que cria um novo array com todos os elementos inicializados para um valor especificado.

In [ ]:
# cria uma matrix com 2 linhas e 3 colunas preechidas com o valor 4

np.full(shape=(2, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [ ]:
# criando uma matrix de 5s a partir do shape de outra matriz
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

array_fives = np.full_like(array, fill_value=5)
array_fives

array([[5, 5, 5],
       [5, 5, 5]])

### `np.empty`

O `np.empty` é uma função do módulo NumPy que cria um novo array sem inicializar os elementos. Os elementos contidos no array são valores que já estavam em memória. O np.empty é útil para instanciar grandes arrays rapidamente, já que apenas o endereço de memória é reservado e nenhum valor é inicializado.

In [ ]:
np.empty(shape=(2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

### `np.eye`

O `np.eye` é uma função do módulo NumPy que cria uma matriz identidade, ou seja, uma matriz, <b>não necessariamente quadrada</b>, com elementos iguais a 1 na diagonal principal (que vai do canto superior esquerdo ao canto inferior direito) e 0 em todos os outros elementos.

In [ ]:
np.eye(N=5) # N = número de linhas

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(N=5, M=3) # N = número de linhas, M = Número de colunas

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `np.identity`

O `np.identity` é uma função do módulo NumPy que cria uma matriz identidade, ou seja, uma matriz, <b>obrigatoriamente quadrada</b>, com elementos iguais a 1 na diagonal principal (que vai do canto superior esquerdo ao canto inferior direito) e 0 em todos os outros elementos.

In [ ]:
np.identity(n=5) # n = ordem da matriz quadrada

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

A documentação completa sobre a criação de arrays preenchidos a partir do shape e de um valor pode ser encontrada aqui: https://numpy.org/doc/stable/reference/routines.array-creation.html#from-shape-or-value

### `np.arange`

O `np.arange` é uma função do módulo NumPy que cria um array contendo uma sequência de números, similar à função range do Python, mas retornando um array do NumPy em vez de uma lista.

In [ ]:
np.arange(stop=10) # cria um array com numeros de 0 a 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=3, stop=10) # cria um array com numeros de 3 a 9

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=3, stop=10, step=2) # cria um array com numeros de 3 a 9 pulando de 2 em 2

array([3, 5, 7, 9])

In [ ]:
np.arange(start=10, stop=3, step=-2) # cria um array com numeros de 10 a 3 pulando de 2 em 2

array([10,  8,  6,  4])

In [ ]:
np.arange(start=3, stop=5, step=0.25) # cria um array com numeros de 3.0 a 5.0 pulando de 0.25 em 0.25

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

### `np.linspace`

A função `np.linspace` do módulo NumPy gera um array contendo uma sequência de números igualmente espaçados em um intervalo especificado.

In [ ]:
# cria um array com 4 elementos com valores entre 1 e 10 igualmente espaçados

np.linspace(start=1, stop=10, num=4)

array([ 1.,  4.,  7., 10.])

In [ ]:
# cria um array com 7 elementos com valores entre 1 e 10 igualmente espaçados

np.linspace(start=1, stop=10, num=7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### `np.logspace`

A função `np.logspace` do módulo NumPy gera um array de números espaçados logaritmicamente em uma determinada base.

In [ ]:
# a base padrão é 10, desse modo: [10¹, 10², 10³, 10⁴]
np.logspace(start=1, stop=4, num=4)

array([   10.,   100.,  1000., 10000.])

### `np.geomspace`

 A função `np.geomspace` gera uma sequência de números espaçados geometricamente entre dois valores dados.

In [ ]:
np.geomspace(start=10, stop=10_000, num=4)

array([   10.,   100.,  1000., 10000.])

In [ ]:
np.geomspace(start = 3, stop=48_000, num = 6).astype(int)

array([    3,    20,   144,   999,  6924, 48000])

Outros inicializadores de arrays a partir de intervalos mais técnicos podem ser encontrados na documentação: https://numpy.org/doc/stable/reference/routines.array-creation.html#numerical-ranges