# Álgebra linear

## Produtos matriciais e vetores

In [2]:
import numpy as np

# criando um gerador de números aleatórios
rng = np.random.default_rng(seed=2)

In [3]:
# criando o vetor 1
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([ 6, -5, -8, -5])

In [4]:
# criando o vetor 2
vector_2 = rng.integers(low=-10, high=10, size=4)
vector_2

array([-2,  6, -1, -9])

In [5]:
# criando a matriz 1
matrix_1 = rng.integers(low=-10, high=10, size=12).reshape(4, 3)
matrix_1

array([[-4,  2,  6],
       [ 4,  9, -7],
       [ 7, -9,  1],
       [-5, -6,  3]])

In [6]:
# criando a matriz 2
matrix_2 = rng.integers(low=-10, high=10, size=12).reshape(3, 4)
matrix_2

array([[-4,  1, -5, -7],
       [ 4, -2,  3,  3],
       [ 8, -2, -6,  2]])

In [7]:
# criando a matriz 3
matrix_3 = rng.integers(low=-10, high=10, size=12).reshape(4, 3)
matrix_3

array([[  8,   9,   7],
       [  3,  -3,  -3],
       [-10,  -7,  -4],
       [ -4,   1,   0]])

In [8]:
# criando a matriz 4
matrix_4 = rng.integers(low=-10, high=10, size=9).reshape(3, 3)
matrix_4

array([[ 3,  7,  7],
       [ 5,  9, -4],
       [ 8,  8, -6]])

### `np.dot`

In [9]:
# calcula o produto interno entre dois vetores
# o resultado é um escalar
np.dot(vector_1, vector_2)

11

In [11]:
matrix_1

array([[-4,  2,  6],
       [ 4,  9, -7],
       [ 7, -9,  1],
       [-5, -6,  3]])

In [12]:
matrix_2

array([[-4,  1, -5, -7],
       [ 4, -2,  3,  3],
       [ 8, -2, -6,  2]])

In [14]:
# calcula também o produto matricial (multiplicação entre duas matrizes)
# o formato deve ser compatível com a multiplicação de matrizes
# o resultado é uma matriz
np.dot(matrix_1, matrix_2)

array([[ 72, -20, -10,  46],
       [-36,   0,  49, -15],
       [-56,  23, -68, -74],
       [ 20,   1, -11,  23]])

In [15]:
matrix_2

array([[-4,  1, -5, -7],
       [ 4, -2,  3,  3],
       [ 8, -2, -6,  2]])

In [16]:
vector_1

array([ 6, -5, -8, -5])

In [17]:
# É possível fazer a multiplicação de um tensor
# por um vetor, nesse caso a multiplicação é feita
# será retornado a soma do produto através do ultimo
# eixo do tensor e o vetor.
np.dot(matrix_2, vector_1)

array([46, -5, 96])

### `np.vdot`

In [18]:
# retorna o produto interno (escalar) entre dois
# funciona como np.dot, mas aceita somente vetores
np.vdot(vector_1, vector_2)

11

### `np.inner`

In [19]:
# retorna o produto interno (escalar) entre dois
# funciona como np.dot e np.vdot
np.inner(vector_1, vector_2)

11

In [20]:
matrix_1

array([[-4,  2,  6],
       [ 4,  9, -7],
       [ 7, -9,  1],
       [-5, -6,  3]])

In [21]:
matrix_2

array([[-4,  1, -5, -7],
       [ 4, -2,  3,  3],
       [ 8, -2, -6,  2]])

In [22]:
# quando usada com matrizes faz a multiplicação entre elas
np.inner(matrix_1, matrix_3)

array([[ 28, -36,   2,  18],
       [ 64,   6, -75,  -7],
       [-18,  45, -11, -37],
       [-73,  -6,  80,  14]])

### `np.outer`

In [23]:
# calcula o produto externo entre dois vetores
np.outer(vector_1, vector_2)

array([[-12,  36,  -6, -54],
       [ 10, -30,   5,  45],
       [ 16, -48,   8,  72],
       [ 10, -30,   5,  45]])

### `np.matmul`

In [24]:
# calcula o produto matricial entre dois arrays
# se forem dois vetores, calcula o produto interno
np.matmul(vector_1, vector_2)

11

In [25]:
# calcula o produto matricial entre dois arrays
# se forem dusa matrizes calcula o produto matricial
np.matmul(matrix_1, matrix_2)

array([[ 72, -20, -10,  46],
       [-36,   0,  49, -15],
       [-56,  23, -68, -74],
       [ 20,   1, -11,  23]])

### `np.linalg.det`

In [26]:
matrix_4

array([[ 3,  7,  7],
       [ 5,  9, -4],
       [ 8,  8, -6]])

In [27]:
# retorna o determinante de um array
# só funciona para arrays quadrados de no mínimo duas dimensões
np.linalg.det(matrix_4)

-304.00000000000006

### `np.linalg.inv`

In [28]:
# calcula a matriz inversa
# a operação só é definida para matrizes quadradas
np.linalg.inv(matrix_4)

array([[ 0.07236842, -0.32236842,  0.29934211],
       [ 0.00657895,  0.24342105, -0.15460526],
       [ 0.10526316, -0.10526316,  0.02631579]])

---

Outras funções com aplicações mais técnicas estão disponíveis conforme a documentação: https://numpy.org/doc/stable/reference/routines.linalg.html#linear-algebra-numpy-linalg