# Indexing, Slicing e Assigning

## Indexing


In [ ]:
import numpy as np

In [ ]:
# criando uma lista 3D
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]
    ]
]

array_3d = np.array(list_3d)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
array_3d.shape

(2, 4, 3)

In [ ]:
# acessando o segundo elemento da lista 'list_3d'
list_3d[1]

[[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]

In [ ]:
# acessando o segundo elemento (profundidade) do array
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [ ]:
# acessando somente uma linha (profundidade 1, linha 3)
array_3d[1][2]

array([19, 20, 21])

In [ ]:
# acessando somente um elemento (profundidade 1, linha 3, coluna 0)
array_3d[1][2][0]

19

In [ ]:
# acessando somente um elemento (profundidade 1, linha 3, coluna 1)
array_3d[1][2][1]

20

In [ ]:
# outra forma de acesso: acessando mais de um valor do eixo (profundidade 1, linha 1)
array_3d[0, 1]

array([4, 5, 6])

In [ ]:
# outra forma de acesso: passando uma lista de profundidades (profundidade 0 e 1)
array_3d[[0, 1]]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# utilizando ' : ' para acessar elementos de um eixo
# (para todos os eixos retornar linha 0 e linha 1)
array_3d[:,[0, 1]]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# utilizando notação negativa para acessar elementos
# acessando a última profundidade e última linha
array_3d[-1, -1]

array([22, 23, 24])

In [ ]:
# utilizando notação negativa para acessar elementos
# acessando a última profundidade, última linha e últiimo elemento
array_3d[-1, -1, -1]

24

In [ ]:
# utilizando notação negativa para acessar elementos
# acessando a última profundidade e penúltima linha
array_3d[-1, -2]

array([19, 20, 21])

In [ ]:
# definindo uma mascara para acessar os elementos

# acessando a primeira profundidade (True) e ignorando a segunda profundidade (False)
mask = [True, False]
array_3d[mask]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# acessando as duas profunidades
mask = [True, True]
array_3d[mask]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# criando uma mascara booleana para retornar elementos que atendam
# determinadas condições

mask = array_3d % 2 == 0
mask

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]]])

In [ ]:
# selecionando os numeros pares com a mascara criadas
array_3d[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## Slicing

In [ ]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# selecionando todos os elementos do eixo da profundidade com ' : '
array_3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# selecionando somente o primerio elemento do eixo da profundidade com ' : '
array_3d[:1]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# selecionando todos os elementos do eixo da profundidade com ' : '
array_3d[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# selecionando todos os elementos do eixo da profundidade
# e da linha 1 até a linha 2 do eixo das linhas
array_3d[:, 1: 3]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [ ]:
# selecionando todos os elementos do eixo da profundidade
# da linha 1 até a linha 2 do eixo das linhas
# e somente a última coluna
array_3d[:, 1: 3, -1]

array([[ 6,  9],
       [18, 21]])

In [ ]:
# selecionando todos os elementos do eixo da profundidade
# da linha 1 até a linha 2 do eixo das linhas
# e da coluna 0 até a penúltima coluna
array_3d[:, 1: 3, :-1]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]]])

In [ ]:
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# selecionando o primeiro elemento do eixo da profundidade
# da linha 1 até a linha 4 do eixo das linhas em passos de 2 (step)
array_3d[0, 1: 4: 2]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
# selecionando o primeiro elemento do eixo da profundidade
# a partir da linha 1 em passos de 2 (step)
# gera o mesmo resultado anterior
array_3d[0, 1::2]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
# selecionando o primeiro elemento do eixo da profundidade
# a partir da linha 0 (inicio) em passos de 2 (step)
array_3d[0, ::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# selecionando o primeiro elemento do eixo da profundidade
# de trás para frente em passos de 2 (step)
array_3d[0, ::-2]

array([[10, 11, 12],
       [ 4,  5,  6]])

In [ ]:
# selecionando o primeiro elemento do eixo da profundidade
# de trás para frente em passos de 1 (step)
# retorna as linhas de trás para frente
array_3d[0, ::-1]

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

## Assigning (alterar valores)

In [ ]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# acessando o segunda profundidade
# segunda linha
# primeiro elemento
array_3d[1][2][0]

19

In [ ]:
# outra forma de acesso já vista
# acessando o segunda profundidade
# segunda linha
# primeiro elemento
array_3d[1, 2, 0]

19

In [ ]:
# alterando o valor (assigning)
array_3d[1, 2, 0] = 50
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [50, 20, 21],
        [22, 23, 24]]])

In [ ]:
# selecionando todos as profundidades
# da linha 1 até a linha 2
# todas as colunas menos a última coluna
array_3d[:, 1:3, :-1]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [50, 20]]])

In [ ]:
# em seguida definindo novos valores para os valores acima
array_3d[:, 1:3, :-1] = [
    [
        [ 4,  5],
        [ 7,  8]
    ],
     [
        [16, 17],
        [50, 20]
    ]
]

array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [50, 20, 21],
        [22, 23, 24]]])

In [ ]:
# buscando a profundidade 0
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Alterando todos os valores da profundidade 0
array_3d[0] = 99
array_3d

array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]],

       [[13, 14, 15],
        [16, 17, 18],
        [50, 20, 21],
        [22, 23, 24]]])

# Exercícios

Neste exercício vamos trabalhar com um array 3D, que representa o desempenho de atletas de corrida.

Na primeira dimensão (profundidade), vamos representar 3 dias de avaliação diferentes. Na segunda dimensão (linhas), cada um dos 5 atletas. Na terceira dimensão (colunas), cada uma das 4 voltas na pista de corrida. Os valores serão dados em segundos.

Estes dados serão simulados com o código abaixo, mas não se preocupe em entendê-lo por enquanto.

In [ ]:
import numpy as np

In [ ]:
rng = np.random.default_rng(seed=1)

In [ ]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3, 5, 4).round(3)
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [ ]:
array.shape

(3, 5, 4)

👆 Observe pelo `shape` que são 3 dias, 5 atletas e 4 voltas.

Dada a definição deste array apresentada acima, você pode entender a primeira linha:
```
[51.037, 52.465, 50.991, 46.091]
```
como o desempenho do primeiro atleta, no primeiro dia, nas 4 voltas da pista.

A sétima linha:
```
[41.867, 44.333, 49.476, 48.733]
```
é o desempenho do segundo atleta no segundo dia, nas 4 voltas da pista.

## Indexing

Dado o array acima, utilize indexação para recuperar o desempenho do terceiro atleta no segundo dia.


In [ ]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [ ]:
array[1, 2]

array([50.641, 50.652, 56.354, 46.664])

Agora recupere o desempenho de todos os atletas na última volta do primeiro dia. Use indexação negativa para acessar a última volta.

In [ ]:
array[0, :, -1]

array([46.091, 51.743, 51.64 , 51.797, 49.228])

Agora recupere o desempenho do segundo e do quarto atletas, no terceiro dia, na segunda volta.

In [ ]:
array[2, [1, 3], 1]

array([50.286, 48.496])

Usando indexação negativa, recupere o desempenho de todos os atletas em todos os dias, na penúltima volta.

In [ ]:
array[:, :, -2]

array([[50.991, 48.389, 50.085, 48.554, 47.654],
       [53.882, 49.476, 56.354, 51.94 , 50.502],
       [49.784, 50.107, 50.963, 52.637, 46.254]])

Crie uma máscara booleana para representar somente os resultados menores que 46. Depois utilize esta máscara para filtrar do array os resultados que atendem a esta condição.

In [ ]:
mask = array < 46
mask

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [ True,  True, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [ ]:
array[mask]

array([41.867, 44.333, 45.056])

## Slicing

Utilize fatiamento para recuperar o desempenho do quarto atleta nas duas primeiras voltas, em todos os dias.

In [ ]:
array[:, 3, :2]

array([[47.791, 49.511],
       [48.867, 56.128],
       [52.195, 48.496]])

Agora recupere o desempenho de todos os atletas nos dois primeiros dias, da segunda volta em diante.

In [ ]:
array[:2, :, 1:]

array([[[52.465, 50.991, 46.091],
        [51.339, 48.389, 51.743],
        [50.882, 50.085, 51.64 ],
        [49.511, 48.554, 51.797],
        [49.123, 47.654, 49.228]],

       [[49.173, 53.882, 53.02 ],
        [44.333, 49.476, 48.733],
        [50.652, 56.354, 46.664],
        [56.128, 51.94 , 51.989],
        [45.056, 50.502, 50.327]]])

Utilize a notação negativa e a notação de "passo" para recuperar os desempenhos dos dois últimos atletas, no segundo dia, nas voltas de índice ímpar.

In [ ]:
array[1, -2:, 1::2]

array([[56.128, 51.989],
       [45.056, 50.327]])

## Assigning

Suponha que o segundo atleta tenha sido desclassificado na prova do terceiro dia, e você deve demonstrar isso no array mudando todos os valores de suas voltas para o número 99.

Utilize a técnica de assigning para fazer esta correção, e exiba o array modificado.

In [ ]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [ ]:
array[2, 1, :] = 0.0
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [ 0.   ,  0.   ,  0.   ,  0.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

A terceira volta dos dois primeiros atletas no segundo dia foi registrada errada, os valores corretos são 53.872 e 49.479. Faça a correção e exiba o array modificado.

In [ ]:
array[1, :2, 2] = [53.872, 49.479]
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 53.872, 53.872, 53.02 ],
        [41.867, 49.479, 49.479, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [ 0.   ,  0.   ,  0.   ,  0.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])