# Funções de indexação

## `np.nonzero`

Retorna os índices do array que são diferentes de zero.

In [2]:
import numpy as np

In [3]:
# definindo um array 2D
array = np.array([[1, 0, 0],
                  [0, 2, 0],
                  [3, 4, 0]])

In [4]:
indices = np.nonzero(array)
indices


(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [5]:
# retornando os valores diferentes de zero
array[indices]

array([1, 2, 3, 4])

## `np.where`

Filtra o array com base em condições

In [6]:
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# retorna os elementos maiores que 5
np.where(array_1d > 5)

(array([6, 7, 8, 9]),)

In [8]:
# retorna os elementos menores que 4
# se for menor, o valor é substituído por 0
# se for maior, o valor é substituído por 1
np.where(array_1d < 4, 0 , 1)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [9]:
# retorna os elementos menores que 4
# se for menor, permanece os mesmos valores do original
# se for maior, o valor é substituído pelo valor original + 10
np.where(array_1d < 4, array_1d, array_1d + 10)

array([ 0,  1,  2,  3, 14, 15, 16, 17, 18, 19])

In [10]:
# cria um novo array
other_array_1d = np.arange(50, 60)
other_array_1d

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [13]:
# retorna os elementos menores que 4
# se for menor, permanece os mesmos valores do original
# se for maior, o valor é substituído pelo valor do outro array
np.where(array_1d < 4, array_1d, other_array_1d)

array([ 0,  1,  2,  3, 54, 55, 56, 57, 58, 59])

In [12]:
# criando um array 2D
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
# verifica se o valor é par
# se for par, permanece os mesmos valores do original
# se for impar, o valor é substituído pelo valor do outro array
np.where(array_2d % 2 == 0, array_2d, -1)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1]])

## `np.argwhere`

Retorna os índices do array que satisfazem determinadas condições.

In [15]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
# retorna os índices dos números pares
np.argwhere(array_2d % 2 == 0)

array([[0, 0],
       [0, 2],
       [0, 4],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [2, 4],
       [3, 1],
       [3, 3]])

## `np.select`

Funciona como a ``np.where``, mas permite checar mais de uma condição.

In [17]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# retorna os elementos menores que 4 (condição 1)
# retorna os elementos maiores que 7 (condição 2)
# se a primeira condição verdadeira, o valor é subistituído pelo original + 10
# se a segunda condição verdadeira, o valor é subistituído pelo original + 20
# se nenhuma das condições forem verdadeira, o valor é subistituido por -1
np.select(
    condlist=[array_1d < 4, array_1d > 7],
    choicelist=[array_1d + 10, array_1d + 20],
    default=-1)

array([10, 11, 12, 13, -1, -1, -1, -1, 28, 29])

## `np.unravel_index`

Retorna o índice linearizado, ou seja, a posição absoluta do elemento no array.

In [20]:
# definindo um array 2D
shape = (4, 5)
array = np.arange(20).reshape(shape)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
# retorna as coordenadas do elemento de índice 12
np.unravel_index(indices=12, shape=shape)

(2, 2)

## `np.diag_indices`

Retorna n-índices da diagonal principal de um array quadrado.

In [23]:
indices = np.diag_indices(n=3, ndim=2)
indices

(array([0, 1, 2]), array([0, 1, 2]))

In [24]:
# definindo um array 3x3
array = np.arange(0, 9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# substitui os valores da diagonal principal por -1
array[indices] = -1
array

array([[-1,  1,  2],
       [ 3, -1,  5],
       [ 6,  7, -1]])

## `np.tril_indices`

Retorna os indices do triângulo inferior de um array 2D quadrado.

In [26]:
indices = np.tril_indices(n=3, m=3)
indices

(array([0, 1, 1, 2, 2, 2]), array([0, 0, 1, 0, 1, 2]))

In [27]:
# definindo um novo array
array = np.arange(0, 9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# retornando os valore do tringulo inferior
# muda os valores para -1
array[indices] = -1
array

array([[-1,  1,  2],
       [-1, -1,  5],
       [-1, -1, -1]])

## `np.triu_indices`


Retorna o triângulo superior de um array.

In [31]:
indices = np.triu_indices(n=3, m=3)
indices

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))

In [32]:
# definindo um novo array
array = np.arange(0, 9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
# retornando os valore do tringulo superior
# muda os valores para -1
array[indices] = -1
array

array([[-1, -1, -1],
       [ 3, -1, -1],
       [ 6,  7, -1]])

## `np.diag_indices_from`

Funciona como ``diag_indices``, mas ao invés de passar as dimensões do array, passamos o próprio array como parâmetro.

In [34]:
# retorna os índices da diagonal principal
np.diag_indices_from(array)

(array([0, 1, 2]), array([0, 1, 2]))

## `np.tril_indices_from`

Funciona como ``tril_indices``, mas ao invés de passar as dimensões do array, passamos o próprio array como parâmetro.

In [35]:
# retorna os índices do triangulo inferior
np.tril_indices_from(array)

(array([0, 1, 1, 2, 2, 2]), array([0, 0, 1, 0, 1, 2]))

## `np.triu_indices_from`

Funciona como ``triu_indices``, mas ao invés de passar as dimensões do array, passamos o próprio array como parâmetro.

In [36]:
# retorna os índices do triangulo superior
np.triu_indices_from(array)

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))