# Funções de Manipulação

## Agrupando e dividindo arrays

In [1]:
import numpy as np

In [2]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array_1_2d = np.arange(0, 18).reshape(3, 6)
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [4]:
array_2_2d = np.arange(18, 36).reshape(3, 6)
array_2_2d

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### `np.concatenate`

Concatena dois ou mais arrays.

In [5]:
# por padrão o numpy concatena no eixo das linhas
np.concatenate([array_1_2d, array_2_2d])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
# concatenando no eixo das colunas
np.concatenate([array_1_2d, array_2_2d], axis=1)

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### `np.stack`

Empilha os arrays e cria uma nova dimensão para a pilha gerada.

In [7]:
# por padrão o axis é igual a 0
array_stacked = np.stack(arrays=[array_1_2d, array_2_2d])
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [8]:
# foi criada a dimensão da profundidade
array_stacked.shape

(2, 3, 6)

In [9]:
# ao especificar axis = 1 é feita a combinação
# da primeira linha da primeira matriz com a primeira linha da segunda matriz
# e assim por diante.

array_stacked = np.stack(arrays=[array_1_2d, array_2_2d], axis=1)
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [18, 19, 20, 21, 22, 23]],

       [[ 6,  7,  8,  9, 10, 11],
        [24, 25, 26, 27, 28, 29]],

       [[12, 13, 14, 15, 16, 17],
        [30, 31, 32, 33, 34, 35]]])

In [10]:
array_stacked.shape

(3, 2, 6)

In [11]:
# ao expecificar axis = -1 é feita a combinação
# da primeira linha da primeira matriz com a primeira linha da segunda matriz
# e assim por diante, em que cada combinação de linhas, viram colunas.

array_stacked = np.stack(arrays=[array_1_2d, array_2_2d], axis=-1)
array_stacked

array([[[ 0, 18],
        [ 1, 19],
        [ 2, 20],
        [ 3, 21],
        [ 4, 22],
        [ 5, 23]],

       [[ 6, 24],
        [ 7, 25],
        [ 8, 26],
        [ 9, 27],
        [10, 28],
        [11, 29]],

       [[12, 30],
        [13, 31],
        [14, 32],
        [15, 33],
        [16, 34],
        [17, 35]]])

In [12]:
array_stacked.shape

(3, 6, 2)

### `np.vstack`

Mesmo resultado de ``np.concatenate`` com axis=0.

In [13]:
np.vstack(tup=[array_1_2d, array_2_2d])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### `np.hstack`

Mesmo resultado de ``np.concatenate`` com axis=1.

In [14]:
np.hstack(tup=[array_1_2d, array_2_2d])

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

### `np.split`

Faz a divisão do array.

In [15]:
# indices_or_sections deve ser um valor que resulte
# em arrays de tamanhos iguais
np.split(ary=array_1d, indices_or_sections=2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [16]:
# por padrão a divisão é feita no eixo das linhas
np.split(ary=array_1_2d, indices_or_sections=3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [17]:
# dividindo no eixo das colunas
np.split(ary=array_1_2d, indices_or_sections=3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [18]:
# dividindo no eixo das colunas após os indices 2 e 3
np.split(ary=array_1_2d, indices_or_sections=[2, 3], axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

### `np.vsplit`

In [19]:
# divide no eixo das linhas
np.vsplit(ary=array_1_2d, indices_or_sections=3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

### `np.hsplit`

In [20]:
# divide no eixo das colunas
np.hsplit(ary=array_1_2d, indices_or_sections=3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [21]:
# divide no eixo das colunas
np.hsplit(ary=array_1_2d, indices_or_sections=[2, 3])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

## Adicionando Eixos

### `np.expand_dims`

In [22]:
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [23]:
array_1_2d.ndim

2

In [24]:
array_1_2d.shape

(3, 6)

In [25]:
# adicionando a dimensão de profundidade
# observar o numero de colchetes (aumentou)
new_array_2d = np.expand_dims(a=array_1_2d, axis=0)
new_array_2d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]])

In [26]:
new_array_2d.ndim

3

In [27]:
new_array_2d.shape

(1, 3, 6)

In [28]:
# Expande as dimensões das linhas
new_array_2d = new_array_2d = np.expand_dims(a=array_1_2d, axis=1)
new_array_2d

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]]])

In [29]:
new_array_2d.ndim

3

In [30]:
new_array_2d.shape

(3, 1, 6)

## Rearranjando elementos

### `np.flip`

In [31]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# rearanja o array em ordem inversa
np.flip(array_1d)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
# rearanja o array em ordem inversa
np.flip(array_1_2d)

array([[17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [34]:
# rearanja o array em ordem inversa somente as linhas
np.flip(array_1_2d, axis=0)

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [35]:
# rearanja o array em ordem inversa somente as colunas
np.flip(array_1_2d, axis=1)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12]])

### `np.resize`

Muda as dimensões do array. Ao contrário do ``reshape`` permite dimensões inválidas.

In [36]:
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [37]:
np.resize(a=array_1_2d, new_shape=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# usa os valores para atender o novo shape
# e descarta os outros elementos
np.resize(a=array_1_2d, new_shape=(4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
# usa os valores e repete os valores
# para atender o novo shape
np.resize(a=array_1_2d, new_shape=(8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [40]:
# usa os valores e repete os valores
# para atender o novo shape
np.resize(a=array_1_2d, new_shape=(2, 5, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

## Adicionando ou removendo elementos

### `np.insert`

In [41]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# obj = índice que o valor vai ser colocado
# o restante do array é movido para a direita
np.insert(arr=array_1d, obj=4, values=10)

array([ 0,  1,  2,  3, 10,  4,  5,  6,  7,  8,  9])

In [43]:
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [44]:
# obj = índice que o valor vai ser colocado
# axis = 1 será criada uma coluna com o valor especificado
# as outros colunas serão movidas para a direita
np.insert(arr=array_1_2d, obj=1, values=-1, axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -1,  7,  8,  9, 10, 11],
       [12, -1, 13, 14, 15, 16, 17]])

In [45]:
# obj = índice que o valor vai ser colocado
# axis = 1 será criada uma coluna com os valores especificado
# as outros colunas serão movidas para a direita
np.insert(arr=array_1_2d, obj=1, values=[-1, -2, -3], axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -2,  7,  8,  9, 10, 11],
       [12, -3, 13, 14, 15, 16, 17]])

### `np.delete`

In [46]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# apaga o elemento do índica 4
# o restante do array é movido para a esquerda
np.delete(arr=array_1d, obj=4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [48]:
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [49]:
# a coluna de indice 1 será apagada e o restante
# será movido para a direita
np.delete(arr=array_1_2d, obj=1, axis=1)

array([[ 0,  2,  3,  4,  5],
       [ 6,  8,  9, 10, 11],
       [12, 14, 15, 16, 17]])

In [50]:
# a linha de indice 1 será apagada e o restante
# será movido para cima
np.delete(arr=array_1_2d, obj=1, axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

### `np.append`

In [51]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# adicionando uma lista de valores ao final do array
np.append(arr=array_1d, values=[0, 1, 2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [53]:
array_1_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [54]:
# adicionando nova linha ao final do array
np.append(arr=array_1_2d, values=[[0, 1, 2, 3, 4, 5]], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

In [55]:
# adicionando nova coluna ao final do array
np.append(arr=array_1_2d, values=[[0], [1], [2]], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0],
       [ 6,  7,  8,  9, 10, 11,  1],
       [12, 13, 14, 15, 16, 17,  2]])

### `np.tile`

Repete o array pelo numero de vezes solicitada.


In [56]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Gera um novo array repetindo o array passado 2 vezes
np.tile(A=array_1d, reps=2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Gera um novo array repetindo o array passado
# repete tanto no eixo das linhas como colunas
np.tile(A=array_1d, reps=(2, 2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
# Gera um novo array repetindo o array passado
# repete 3 vezes no eixo das linhas  e duas vezes no eixo das colunas
np.tile(A=array_1_2d, reps=(3, 2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17]])

### `np.pad`

Preenche um array com os valores solicitados

In [60]:
array_pad_1d = np.array([1, 2, 3])
array_pad_1d

array([1, 2, 3])

In [61]:
# pad_width (1, 2) - adiciona 1 constante no inicio e 2 constantes no final
np.pad(array_pad_1d, pad_width=(1,2), mode='constant', constant_values=(10, 25))

array([10,  1,  2,  3, 25, 25])

In [62]:
# pad_width (1, 2) - repete as bordas do array
np.pad(array_pad_1d, pad_width=(1,2), mode='edge')

array([1, 1, 2, 3, 3, 3])

In [63]:
# preenche com o valor mínimo
np.pad(array_pad_1d, pad_width=(1,2), mode='minimum')

array([1, 1, 2, 3, 1, 1])

In [64]:
# preenche com o valor máximo
np.pad(array_pad_1d, pad_width=(1,2), mode='maximum')

array([3, 1, 2, 3, 3, 3])

In [65]:
# preenche com a média dos valores
np.pad(array_pad_1d, pad_width=(1,2), mode='mean')

array([2, 1, 2, 3, 2, 2])

In [66]:
array_pad_2d = np.array([[1, 2],
                         [3, 4]])

In [67]:
np.pad(array = array_pad_2d, pad_width=(1,2), mode='reflect')

array([[4, 3, 4, 3, 4],
       [2, 1, 2, 1, 2],
       [4, 3, 4, 3, 4],
       [2, 1, 2, 1, 2],
       [4, 3, 4, 3, 4]])

💡 Outros modos podem ser checados na documentação: https://numpy.org/doc/stable/reference/generated/numpy.pad.html#numpy-pad

### `np.trim_zeros`

Remove os valores zerados do array

In [68]:
array_with_zeros = np.array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])
array_with_zeros

array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0])

In [69]:
np.trim_zeros(filt = array_with_zeros)

array([1, 2, 3, 4, 5])

In [70]:
# remove os zeros do inicio do array (front)
# mantendo os zeros do final
np.trim_zeros(filt=array_with_zeros, trim= 'f')

array([1, 2, 3, 4, 5, 0, 0, 0])

In [71]:
# remove os zeros do final do array (back)
# mantendo os zeros do início
np.trim_zeros(filt=array_with_zeros, trim= 'b')

array([0, 0, 1, 2, 3, 4, 5])

## Obtendo valores únicos

### `np.unique`

In [73]:
array_unique = np.array([7, 8, 8, 6, 8, 7, 7])

In [74]:
# obtendo os valores únicos
np.unique(ar=array_unique)

array([6, 7, 8])

In [75]:
# obtendo os valores únicos e os ídices desses valores
np.unique(ar=array_unique, return_index=True)

(array([6, 7, 8]), array([3, 0, 1]))

In [76]:
# retorna os valores únicos e as posições caso você queira reconstruir o array
unique_values, indices = np.unique(ar=array_unique, return_inverse = True)
unique_values, indices

(array([6, 7, 8]), array([1, 2, 2, 0, 2, 1, 1]))

In [77]:
# reconstruindo o array
unique_values[indices]

array([7, 8, 8, 6, 8, 7, 7])

In [78]:
# verificando quantas vezes cada elemento aparece no array
np.unique(ar=array_unique, return_counts = True)

(array([6, 7, 8]), array([1, 3, 3]))

In [79]:
# definindo uma matriz
array_unique_2d = np.array([[0, 1, 2],
                            [3, 4, 5],
                            [0, 1, 2]])

In [80]:
# retornando os elementos únicos e verificando quantas vezes eles aparecem na matrix
np.unique(ar=array_unique_2d, return_counts = True)

(array([0, 1, 2, 3, 4, 5]), array([2, 2, 2, 1, 1, 1]))

In [83]:
# retorna as linhas sem repetir (únicas) e a quantidade de vezes que elas aparecem no array
np.unique(ar=array_unique_2d, return_counts=True, axis=0)

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([2, 1]))