# Estatística

In [2]:
import numpy as np

rng = np.random.default_rng(seed=5)

In [3]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([  3,   6, -10,   6])

In [4]:
matrix_1 = rng.integers(low=-10, high=10, size=12).reshape(4, 3)
matrix_1

array([[ -1,   0,   2],
       [ -5,   9,  -9],
       [ -5,  -3,   1],
       [ -2,  -8, -10]])

### `np.percentile`

In [5]:
# retorna o percentil solicitado
np.percentile(vector_1, q=10)

-6.1

In [7]:
np.percentile(vector_1, q=50) # 50% = mediana

4.5

In [8]:
np.percentile(vector_1, q=90)

6.0

In [11]:
# obtendo os percentis de uma matriz
# nesse processo a matriz é linearizada
np.percentile(matrix_1, q=50) # mediana

-2.5

### `np.quantile`

In [12]:
# retorna o quantil solicitado
# o valor deve ser entre 0 e 1
np.quantile(vector_1, q=0.1) #10% dos dados

-6.1

In [13]:
np.quantile(vector_1, q=0.5) #mediana

4.5

In [16]:
# utilizando a função em uma matriz
np.quantile(matrix_1, q=0.5) # mediana

-2.5

In [18]:
# obtendo o quantil em determinado eixo
# obtem a mediana de cada linha
np.quantile(matrix_1, q=0.5, axis=1)

array([ 0., -5., -3., -8.])

### `np.median`

In [19]:
# retorna a mediana
np.median(vector_1)

4.5

In [20]:
# retorna a mediana de uma matriz
np.median(matrix_1)

-2.5

In [21]:
# retorna a mediana de uma matriz em determinado eixo
np.median(matrix_1, axis=1)

array([ 0., -5., -3., -8.])

### `np.mean`

In [24]:
# retorna a média dos valores do vetor
np.mean(vector_1)

1.25

In [25]:
# retorna a média dos valores da matriz
np.mean(matrix_1)

-2.5833333333333335

In [26]:
# retorna a média dos valores da matriz em determinado eixo
np.mean(matrix_1, axis=1)

array([ 0.33333333, -1.66666667, -2.33333333, -6.66666667])

### `np.average`

In [29]:
# retorna a média ponderada dos valores do vetor
# a soma dos pesos deve ser igual a 1
np.average(vector_1, weights=[0.15, 0.25, 0.4, 0.2])

-0.8499999999999996

In [30]:
# se não for especificado os pesos, então é retornado a média
np.average(vector_1)

1.25

### `np.std`

In [31]:
# desvio padrão
np.std(vector_1)

6.609652033201143

In [32]:
# média
np.mean(vector_1)

1.25

Isso significa que os valores estão afastados 6.60 unidades da média.

In [33]:
# calculando o desvio padrão de uma matriz
np.std(matrix_1)

5.122797629767894

In [34]:
# calculando o desvio padrão de uma matriz considerando as linhas
np.std(matrix_1, axis=1)

array([1.24721913, 7.7172246 , 2.49443826, 3.39934634])

### `np.var`

In [35]:
# variancia de um vetor
np.var(vector_1)

43.6875

In [36]:
# variancia de uma matriz
np.var(matrix_1)

26.243055555555557

In [37]:
# variancia de uma matriz considerando as linhas
np.var(matrix_1, axis=1)

array([ 1.55555556, 59.55555556,  6.22222222, 11.55555556])

### `np.cov`

In [38]:
vector_1

array([  3,   6, -10,   6])

In [44]:
# calculando a covariancia de uma variável com ela mesma
np.cov(vector_1)

array(58.25)

In [41]:
vector_2 = 2 * vector_1
vector_2

array([  6,  12, -20,  12])

In [43]:
# calculando a covariancia de uma variável com ela mesma
np.cov(vector_2)

array(233.)

In [46]:
# calculando a covariancia entre duas variáveis
# na diagonal principal temos a covariancia do vetor 1 com ele mesmo
# e a convariancia do vetor dois com ele mesmo
np.cov(vector_1, vector_2)

array([[ 58.25, 116.5 ],
       [116.5 , 233.  ]])

## `np.corrcoef`

In [49]:
# Calculando o coeficiente de correlação de Pearson entre dois arrays
# obtem a similaridade entre dois vetores
np.corrcoef(vector_1, vector_1)

array([[1., 1.],
       [1., 1.]])

In [51]:
# Calculuando o coeficiente de correlação de Pearson entre dois arrays
# obtem a similaridade entre dois vetores
# nesse caso é a mesma, pois um vetor é multiplo do outro
np.corrcoef(vector_1, vector_2)

array([[1., 1.],
       [1., 1.]])

### `np.histogram`

In [52]:
# criando um vetor 3
vector_3 = rng.integers(low=-10, high=10, size=100)
vector_3

array([-10, -10,  -8,   9,  -7,   3,   5,  -6,  -5,  -2,  -5,   9,  -7,
         7,   5,   6,  -8,  -3,   2,  -1,   3,   3,   3,  -9,   9,   1,
         8,  -5,  -3,   7,  -7,  -9,  -3,   3,  -8,   7,  -4,  -6,   0,
         7,   7,   7,  -4, -10,   5,   4,   5, -10, -10,   0,  -4,  -2,
         8,  -6,   0,  -4,  -5,   6,  -7,  -4,  -8,  -8,  -5,   3,   1,
        -2,  -7,   5,   5,  -6,  -9,  -4,  -8,   5,   0,   0,  -5,   0,
         9,  -6,   5, -10,  -4,   8,   7,  -9,   6,   6,  -1,  -3,   9,
         9,   3,  -3,  -6,   8,  -5,   1,   3,  -6])

In [55]:
hist, bin_edges = np.histogram(a=vector_3, bins=4)
hist # quantidades de valores no intervalo

array([28, 24, 19, 29])

In [56]:
bin_edges # o primeiro intervalor vai de -10 até -5,25

array([-10.  ,  -5.25,  -0.5 ,   4.25,   9.  ])

In [57]:
# obtendo os valores em formato de densidade
hist, bin_edges = np.histogram(a=vector_3, bins=4, density=True)
hist # quantidades de valores no intervalo

array([0.05894737, 0.05052632, 0.04      , 0.06105263])

In [58]:
bin_edges

array([-10.  ,  -5.25,  -0.5 ,   4.25,   9.  ])

### `np.bincount`

In [59]:
vector_4 = np.arange(6)
vector_4

array([0, 1, 2, 3, 4, 5])

In [61]:
# divide o array em intervalos
# no caso cada intervalo tem comprimento igual a 1
np.bincount(vector_4)

array([1, 1, 1, 1, 1, 1])

In [62]:
# criando um vetor com valores entre 0 e 10
vector_5 = rng.integers(low=0, high=10, size=6)
vector_5

array([3, 7, 1, 6, 9, 6])

In [63]:
np.bincount(vector_5)

array([0, 1, 0, 1, 0, 0, 2, 1, 0, 1])

---

Outras funções estatísticas podem ser checadas na documentação: https://numpy.org/doc/stable/reference/routines.statistics.html

# Constantes

### `np.e`

In [64]:
# constante de euler
np.e

2.718281828459045

### `np.pi`

In [65]:
np.pi

3.141592653589793

### `np.inf`

In [66]:
np.inf

inf

### `np.nan`

In [67]:
np.nan

nan

In [68]:
np.log(-1)

<ipython-input-68-0cd3490738d5>:1: RuntimeWarning: invalid value encountered in log
  np.log(-1)


nan

### `np.newaxis`

In [75]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [76]:
array.shape

(3,)

In [77]:
new_array = array[:, np.newaxis]
new_array

array([[1],
       [2],
       [3]])

In [78]:
new_array.shape

(3, 1)

In [79]:
new_array = array[np.newaxis, :]
new_array

array([[1, 2, 3]])

In [80]:
new_array.shape

(1, 3)