# Funções Universais

Ufunc (*universal functions*) é como o NumPy chama as funções que são aplicadas a cada elemento de um array.

Existe uma infinidade de funções disponíveis, aqui apresentaremos algumas, as demais podem ser consultadas na documentação: https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

## Funções Matemáticas

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=2)

In [3]:
array_1 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [4]:
array_2 = rng.integers(low=-10, high=10, size=20).reshape(4, 5)
array_2

array([[ -4,   1,  -5,  -7,   4],
       [ -2,   3,   3,   8,  -2],
       [ -6,   2,   8,   9,   7],
       [  3,  -3,  -3, -10,  -7]])

### `np.add`

In [5]:
np.add(array_1, array_2)

array([[  2,  -4, -13, -12,   2],
       [  4,   2,  -6,   4,   0],
       [  0,   6,  17,   2,  14],
       [ -6,  -2,  -8, -16,  -4]])

In [6]:
array_1 + array_2

array([[  2,  -4, -13, -12,   2],
       [  4,   2,  -6,   4,   0],
       [  0,   6,  17,   2,  14],
       [ -6,  -2,  -8, -16,  -4]])

In [7]:
# também podemos passar um escalar como argumento
np.add(array_1, 100)

array([[106,  95,  92,  95,  98],
       [106,  99,  91,  96, 102],
       [106, 104, 109,  93, 107],
       [ 91, 101,  95,  94, 103]])

### `np.subtract`

In [8]:
np.subtract(array_1, array_2)

array([[ 10,  -6,  -3,   2,  -6],
       [  8,  -4, -12, -12,   4],
       [ 12,   2,   1, -16,   0],
       [-12,   4,  -2,   4,  10]])

In [9]:
array_1 - array_2

array([[ 10,  -6,  -3,   2,  -6],
       [  8,  -4, -12, -12,   4],
       [ 12,   2,   1, -16,   0],
       [-12,   4,  -2,   4,  10]])

### `np.multiply`

In [10]:
# Multiplicação elemento a elemento
np.multiply(array_1, array_2)

array([[-24,  -5,  40,  35,  -8],
       [-12,  -3, -27, -32,  -4],
       [-36,   8,  72, -63,  49],
       [-27,  -3,  15,  60, -21]])

In [11]:
array_1 * array_2

array([[-24,  -5,  40,  35,  -8],
       [-12,  -3, -27, -32,  -4],
       [-36,   8,  72, -63,  49],
       [-27,  -3,  15,  60, -21]])

###`np.divide`

In [12]:
np.divide(array_1, array_2)

array([[-1.5       , -5.        ,  1.6       ,  0.71428571, -0.5       ],
       [-3.        , -0.33333333, -3.        , -0.5       , -1.        ],
       [-1.        ,  2.        ,  1.125     , -0.77777778,  1.        ],
       [-3.        , -0.33333333,  1.66666667,  0.6       , -0.42857143]])

In [13]:
array_1 / array_2

array([[-1.5       , -5.        ,  1.6       ,  0.71428571, -0.5       ],
       [-3.        , -0.33333333, -3.        , -0.5       , -1.        ],
       [-1.        ,  2.        ,  1.125     , -0.77777778,  1.        ],
       [-3.        , -0.33333333,  1.66666667,  0.6       , -0.42857143]])

###`np.mod`

In [14]:
# resto da divisão de cada elemento por 2
np.mod(array_1, 2)

array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

In [15]:
array_1 % 2

array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

###`np.divmod`

In [16]:
# retorna um array contendo a divisão inteira
# e outro array contendo o resto da divisão inteira
np.divmod(array_1, 2)

(array([[ 3, -3, -4, -3, -1],
        [ 3, -1, -5, -2,  1],
        [ 3,  2,  4, -4,  3],
        [-5,  0, -3, -3,  1]]),
 array([[0, 1, 0, 1, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1],
        [1, 1, 1, 0, 1]]))

###`np.absolute`

In [17]:
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [18]:
# retorna o valor absoluto dos elementos
np.absolute(array_1)

array([[6, 5, 8, 5, 2],
       [6, 1, 9, 4, 2],
       [6, 4, 9, 7, 7],
       [9, 1, 5, 6, 3]])

###`np.diff`

In [19]:
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [20]:
# retorna a diferença entre um valor e o seu próximo
# na posição 1 e 2 respectivamente do original: -4 e 1
# a distância absoluta de um para outro é 5
np.diff(array_1)

array([[-11,  -3,   3,   3],
       [ -7,  -8,   5,   6],
       [ -2,   5, -16,  14],
       [ 10,  -6,  -1,   9]])

In [21]:
# retorna a diferença da diferença
# por padrão n=1
np.diff(array_1, n=2)

array([[  8,   6,   0],
       [ -1,  13,   1],
       [  7, -21,  30],
       [-16,   5,  10]])

###`np.power`

In [22]:
# eleva os valores ao quadrado
np.power(array_1, 2)

array([[36, 25, 64, 25,  4],
       [36,  1, 81, 16,  4],
       [36, 16, 81, 49, 49],
       [81,  1, 25, 36,  9]])

In [23]:

array_1 ** 2

array([[36, 25, 64, 25,  4],
       [36,  1, 81, 16,  4],
       [36, 16, 81, 49, 49],
       [81,  1, 25, 36,  9]])

In [24]:
# eleva as duas primeiras linhas ao quadrado
# eleva as duas ultimas linhas ao cubo
np.power(array_1, [[2], [2], [3], [3]])

array([[  36,   25,   64,   25,    4],
       [  36,    1,   81,   16,    4],
       [ 216,   64,  729, -343,  343],
       [-729,    1, -125, -216,   27]])

In [25]:
# eleva as duas primeiras conlunas ao quadrado
# eleva as três ultimas colunas ao cubo
np.power(array_1, [[2 , 2, 3, 3, 3]])

array([[  36,   25, -512, -125,   -8],
       [  36,    1, -729,  -64,    8],
       [  36,   16,  729, -343,  343],
       [  81,    1, -125, -216,   27]])

###`np.exp`

In [26]:
# calcula os elementos elevados ao numero e = 2.71...
np.exp(array_1)

array([[4.03428793e+02, 6.73794700e-03, 3.35462628e-04, 6.73794700e-03,
        1.35335283e-01],
       [4.03428793e+02, 3.67879441e-01, 1.23409804e-04, 1.83156389e-02,
        7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 8.10308393e+03, 9.11881966e-04,
        1.09663316e+03],
       [1.23409804e-04, 2.71828183e+00, 6.73794700e-03, 2.47875218e-03,
        2.00855369e+01]])

###`np.log`

In [27]:
# calcula o logaritmo dos numeros
# não é possível calcular de numeros negativos, retornando nan
np.log(array_1)

<ipython-input-27-55f2b7cc27c6>:3: RuntimeWarning: invalid value encountered in log
  np.log(array_1)


array([[1.79175947,        nan,        nan,        nan,        nan],
       [1.79175947,        nan,        nan,        nan, 0.69314718],
       [1.79175947, 1.38629436, 2.19722458,        nan, 1.94591015],
       [       nan, 0.        ,        nan,        nan, 1.09861229]])

###`np.reciprocal`

In [28]:
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [29]:
# reciproca = 1 / elemento
np.reciprocal(array_1.astype(float))

array([[ 0.16666667, -0.2       , -0.125     , -0.2       , -0.5       ],
       [ 0.16666667, -1.        , -0.11111111, -0.25      ,  0.5       ],
       [ 0.16666667,  0.25      ,  0.11111111, -0.14285714,  0.14285714],
       [-0.11111111,  1.        , -0.2       , -0.16666667,  0.33333333]])

###`np.sqrt`

In [30]:
# não calcula a raiz quadrada de numeros negativos, retornando nan.
np.sqrt(array_1)

<ipython-input-30-ba0cbb7b3647>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array_1)


array([[2.44948974,        nan,        nan,        nan,        nan],
       [2.44948974,        nan,        nan,        nan, 1.41421356],
       [2.44948974, 2.        , 3.        ,        nan, 2.64575131],
       [       nan, 1.        ,        nan,        nan, 1.73205081]])

###`np.cbrt`

In [31]:
# calculando a raiz cubica
np.cbrt(array_1)

array([[ 1.81712059, -1.70997595, -2.        , -1.70997595, -1.25992105],
       [ 1.81712059, -1.        , -2.08008382, -1.58740105,  1.25992105],
       [ 1.81712059,  1.58740105,  2.08008382, -1.91293118,  1.91293118],
       [-2.08008382,  1.        , -1.70997595, -1.81712059,  1.44224957]])

###`np.gcd`

In [32]:
array_1, array_2

(array([[ 6, -5, -8, -5, -2],
        [ 6, -1, -9, -4,  2],
        [ 6,  4,  9, -7,  7],
        [-9,  1, -5, -6,  3]]),
 array([[ -4,   1,  -5,  -7,   4],
        [ -2,   3,   3,   8,  -2],
        [ -6,   2,   8,   9,   7],
        [  3,  -3,  -3, -10,  -7]]))

In [33]:
# calculando o maior divisor comum entre as duas matrizes
# elemento por elemento
np.gcd(array_1, array_2)

array([[2, 1, 1, 1, 2],
       [2, 1, 3, 4, 2],
       [6, 2, 1, 1, 7],
       [3, 1, 1, 2, 1]])

###`np.lcm`

In [34]:
# calculando o minimo multiplo comum entre as duas matrizes
# elemento por elemento
np.lcm(array_1, array_2)

array([[12,  5, 40, 35,  4],
       [ 6,  3,  9,  8,  2],
       [ 6,  4, 72, 63,  7],
       [ 9,  3, 15, 30, 21]])

## Funções Trigonométricas

### Funções trigonométricas

Retornam as devidas operações trigonométricas nos valores do array. Os valores são interpretados como radianos:

- `np.sin`: seno
- `np.cos`: cosseno
- `np.tan`: tangente
- `np.hypot`: hipotenusa
- `np.arc*`: arco seno, cosseno ou tangente, ex: `np.arcsin`
- `np.*h`: seno, cosseno ou tangente hiperbólica, ex: `np.sinh`
- `np.arc*h`: arco seno, cosseno ou tangente hiperbólica, ex: `np.arcsinh`
- `np.degrees`, `np.rad2deg`: converte ângulos expressos em radianos para graus
- `np.radians`, `np.deg2rad`: converte ângulos expressos em graus para radianos

In [35]:
# calculando pi
pi = np.radians(180)
pi

3.141592653589793

In [36]:
# calculando seno de pi
np.sin(pi)

1.2246467991473532e-16

In [37]:
# calculando cosseno de pi
np.cos(pi)

-1.0

In [38]:
# calculando a tangente hiperbólica de pi
np.tanh(pi)

0.9962720762207499

In [39]:
# calculando o arco-tangente de 1
np.arctan(1)

0.7853981633974483

---

Todas as funções matemáticas disponíveis podem ser consultadas na documentação: https://numpy.org/doc/stable/reference/routines.math.html

## Funções de Comparação

###`np.maximum`

In [40]:
# visualizando o array_1
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [41]:
# visualizando o array_2
array_2

array([[ -4,   1,  -5,  -7,   4],
       [ -2,   3,   3,   8,  -2],
       [ -6,   2,   8,   9,   7],
       [  3,  -3,  -3, -10,  -7]])

In [42]:
# Compara elemento a elemento e retorna o valor máximo
np.maximum(array_1, array_2)

array([[ 6,  1, -5, -5,  4],
       [ 6,  3,  3,  8,  2],
       [ 6,  4,  9,  9,  7],
       [ 3,  1, -3, -6,  3]])

###`np.minimum`

In [43]:
# Compara elemento a elemento e retorna o valor mínimo
np.minimum(array_1, array_2)

array([[ -4,  -5,  -8,  -7,  -2],
       [ -2,  -1,  -9,  -4,  -2],
       [ -6,   2,   8,  -7,   7],
       [ -9,  -3,  -5, -10,  -7]])

###`np.greater`

In [44]:
# Compara elemento a elemento, se o valor do elemento do
# array 1 for maior que o elemento correspondente do array 2
# retorna True
np.greater(array_1, array_2)

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True]])

In [45]:
# equivale a:
array_1 > array_2

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True]])

###`np.greater_equal`

In [46]:
np.greater_equal(array_1, array_2)

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

In [47]:
# equivale a:
array_1 >= array_2

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

###`np.less`

In [48]:
np.less(array_1, array_2)

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True, False,  True, False, False]])

In [49]:
# equivale a:
array_1 < array_2

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True, False,  True, False, False]])

###`np.less_equal`

In [50]:
np.less_equal(array_1, array_2)

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True,  True],
       [ True, False,  True, False, False]])

In [51]:
# equivale a:
array_1 <= array_2

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True,  True],
       [ True, False,  True, False, False]])

###`np.not_equal`

In [52]:
np.not_equal(array_1, array_2)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [53]:
# equivale a:
array_1 != array_2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

###`np.equal`

In [54]:
np.equal(array_1, array_2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [55]:
# equivale a:
array_1 == array_2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

###`np.logical_and`

In [56]:
comparison_1 = array_1 > 0 # valores positivos
comparison_1

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False, False,  True]])

In [57]:
comparison_2 = np.mod(array_1, 2) == 0 # valores pares
comparison_2

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False,  True, False]])

In [58]:
# retornando os valores que são positivos e pares
np.logical_and(comparison_1, comparison_2)

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [59]:
# equivale a:
comparison_1 & comparison_2

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

###`np.logical_or`

In [60]:
# retornando os valores que são positivos ou são pares
np.logical_or(comparison_1, comparison_2)

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

In [61]:
# equivale a:
comparison_1 | comparison_2

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

###`np.logical_xor`

In [62]:
np.logical_xor(comparison_1, comparison_2)

array([[False, False,  True, False,  True],
       [False, False, False,  True, False],
       [False, False,  True, False,  True],
       [False,  True, False,  True,  True]])

###`np.logical_not`

In [63]:
comparison_1


array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False, False,  True]])

In [64]:
comparison_2

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False,  True, False]])

In [65]:
# buscando os valores positivos que não são pares
np.logical_not(comparison_1, comparison_2)

array([[False,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True, False,  True,  True, False]])

###`np.isclose`

In [66]:
array_1 = np.array([-1.1558, 0.8994, 3.2894])
array_2 = np.array([-1.1557, 0.8993, 3.2895])

In [67]:
# verifica elemento a elemento se os valores
# são próximos com base em uma tolerância
np.isclose(a=array_1, b=array_2, atol=0.0001)

array([ True,  True,  True])

###`np.allclose`

In [68]:
# verifica se os arrays são próximos com base em uma tolerância
np.allclose(a=array_1, b=array_2, atol=0.0001)

True

In [69]:
# equivale a:
np.isclose(a=array_1, b=array_2, atol=0.0001).all()

True

###`np.array_equal`

In [70]:
array_1 = np.arange(20).reshape(4, 5)
array_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
array_2 = np.arange(20).reshape(4, 5)
array_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
# verifica se tanto os elementos quanto o shape são iguais
np.array_equal(array_1, array_2)


True

## Funções de Float

### `np.isfinite`

In [76]:
# divide 1 por 0
np.divide(1, 0)

<ipython-input-76-d0750dd256fb>:2: RuntimeWarning: divide by zero encountered in divide
  np.divide(1, 0)


inf

In [77]:
# verifica se a divisão de 1 por 0 é finita
np.isfinite(np.divide(1, 0))

<ipython-input-77-4bde4e7c77e6>:2: RuntimeWarning: divide by zero encountered in divide
  np.isfinite(np.divide(1, 0))


False

### `np.isinf`

In [78]:
# verifica se a divisão de 1 por 0 é infinita
np.isinf(np.divide(1, 0))

<ipython-input-78-99f0659a83e9>:2: RuntimeWarning: divide by zero encountered in divide
  np.isinf(np.divide(1, 0))


True

### `np.isneginf`

In [80]:
# verifica se a divisão de 1 por 0 é infinita negativo
np.isneginf(np.divide(-1, 0))

<ipython-input-80-f5ff88859e8b>:2: RuntimeWarning: divide by zero encountered in divide
  np.isneginf(np.divide(-1, 0))


True

### `np.isnan`

In [81]:
# calcula o log de -1
np.log(-1)

<ipython-input-81-f561d806a0b1>:2: RuntimeWarning: invalid value encountered in log
  np.log(-1)


nan

In [82]:
# verifica se o log de -1 é um nan
np.isnan(np.log(-1))

<ipython-input-82-4e94ca222781>:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(-1))


True

### `np.floor`

In [83]:
# arredonda para baixo
np.floor([-3.6, 2.7, 0.4, 7.0])

array([-4.,  2.,  0.,  7.])

### `np.ceil`

In [84]:
# arredonda para cima
np.ceil([-3.6, 2.7, 0.4, 7.0])

array([-3.,  3.,  1.,  7.])

### `np.trunc`

In [85]:
# arredonda para mais próximo de zero
np.trunc([-3.6, 2.7, 0.4, 7.0])

array([-3.,  2.,  0.,  7.])